const { validationResult } = require('express-validator');
const { errorResponse } = require('../utils/api/rest');

/**
 * Middleware to handle validation errors returned by the express-validator library.
 *
 * @param {Express.Request} req - Express request object.
 * @param {Express.Response} res - Express response object.
 * @param {Express.NextFunction} next - Express next function.
 * @returns {void}
 */
const handleValidationErrors = (req, res, next) => {
  /**
   * Validation errors generated by the express-validator library.
   * @type {Object}
   */
  const errors = validationResult(req);

  if (errors.isEmpty()) return next();

  return errorResponse(res, 422, errors.array());
};

module.exports = {
  handleValidationErrors,
};
